name: Latest blog post workflow
on:
  schedule:
    - cron: "0 * * * *"   # Mondays 00:00 UTC
  workflow_dispatch:
  
permissions:
  actions: write
  pull-requests: write

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "5"
          feed_list: "https://linsnotes.com/feed.xml"
          skip_commit: "true"

      # Commit whatever changed and open/update a PR
      - uses: peter-evans/create-pull-request@v7
        with:
          branch: chore/update-latest-posts
          commit-message: "chore: update latest blog posts"
          title: "chore: update latest blog posts"
          body: "Automated update via blog-post-workflow"
          labels: "automation"
